name: Kotlin PR Checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Set up environment
        run: |
          # Install latest Kotlin and JDK
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
          sdk install java 17.0.10-tem

      - name: Download dependencies
        run: |
          mkdir -p libs
          curl -L -o libs/kotlinx-datetime.jar \
            https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.4.1/kotlinx-datetime-0.4.1.jar

      - name: Compile and test
        run: |
          kotlinc \
            -cp libs/kotlinx-datetime.jar \
            -include-runtime \
            -d test.jar \
            src/main/kotlin/org/example/MathUtils.kt \
            src/main/kotlin/org/example/test/MathUtilsTest.kt
          
          java -cp test.jar:libs/kotlinx-datetime.jar org.example.MathUtilsTestKt || exit 1
