name: Kotlin PR Checks - blank file

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Kotlin
        # You may pin to the exact commit or the version.
        # uses: fwilhe2/setup-kotlin@f5c4ad2f991043954a8c5d6b9d69fbed78e3eba6
        uses: fwilhe2/setup-kotlin@0.2.0
        with:
          # Version of the compiler to download, if not provided a default value is used.
          version: 2.0.0


#      - name: Gradle Android
#        # You may pin to the exact commit or the version.
#        # uses: Raul6469/android-gradle-action@b8fc7c7bde2562a4578b7e1bd996cc78d841638e
#        uses: Raul6469/android-gradle-action@2.0.0

      - name: Run gradle task
        # You may pin to the exact commit or the version.
        # uses: jojo243/android-gradle-action@2b02530cbc017a9b9f3140c81e73c821b21984ea
        uses: jojo243/android-gradle-action@2.1.3


      - name: Download dependencies
        run: |
          mkdir -p libs
          curl -L -o libs/kotlinx-datetime.jar \
            https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.4.1/kotlinx-datetime-0.4.1.jar

      - name: Compile and test
        run: |
          kotlinc \
            -cp libs/kotlinx-datetime.jar \
            -include-runtime \
            -d test.jar \
            src/main/kotlin/org/example/MathUtils.kt \
            src/main/kotlin/org/example/test/MathUtilsTest.kt
          
          java -cp test.jar:libs/kotlinx-datetime.jar org.example.MathUtilsTestKt || exit 1
