name: Kotlin PR Checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Kotlin environment
        run: |
          # Install Kotlin compiler
          sudo apt-get update
          sudo apt-get install -y kotlin

          # Create libs directory for dependencies
          mkdir -p libs
          
          # Download kotlinx-datetime dependency
          curl -L -o libs/kotlinx-datetime.jar \
            https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.4.1/kotlinx-datetime-0.4.1.jar

      - name: Compile and run tests
        run: |
          # Compile main and test files with dependencies
          kotlinc \
            src/main/kotlin/org/example/MathUtils.kt \
            src/main/kotlin/org/example/test/MathUtilsTest.kt \
            -cp libs/kotlinx-datetime.jar \
            -include-runtime \
            -d test.jar
          
          # Run the tests
          java -jar test.jar || exit 1