name: Kotlin PR Checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK (required for Gradle)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download dependencies
        run: |
          mkdir -p libs
          cd libs
          curl -L -O https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.4.1/kotlinx-datetime-0.4.1.jar
          cd ..

      - name: Run Gradle tests
        if: exists('gradlew')
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Compile with dependencies (non-Gradle)
        run: |
          kotlinc \
            src/main/kotlin/org/example/MathUtils.kt \
            src/main/kotlin/org/example/test/MathUtilsTest.kt \
            -cp libs/kotlinx-datetime-0.4.1.jar \
            -include-runtime \
            -d test.jar

      - name: Run tests Jar (non-Gradle)
        run: java -jar test.jar || exit 1