name: Kotlin PR Checks - pr-checks file

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile and test
        run: |
          kotlinc \
            -cp libs/kotlinx-datetime.jar \
            -include-runtime \
            -d test.jar \
            src/main/kotlin/org/example/MathUtils.kt \
            src/main/kotlin/org/example/test/MathUtilsTest.kt
          
          java -cp test.jar:libs/kotlinx-datetime.jar org.example.MathUtilsTestKt || exit 1