name: Kotlin PR Checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3

      - name: Run tests
        #run: kotlinc src/main/kotlin/org/example/MathUtilsTest.kt -include-runtime -d test.jar
        run: kotlinc src/main/kotlin/org/example/MathUtils.kt src/main/kotlin/org/example/test/MathUtilsTest.kt -include-runtime -d test.jar

      - name: Run tests Jar
        run:  java -jar test.jar || exit 1